name: blink_kyc_example
description: Minimal example of the Blink KYC Flutter SDK.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  blink_kyc:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
